all: true
recursive: true
filename: "{{ lower .InterfaceName }}_mock.go"
pkgname: "{{ .SrcPackageName }}_mock"
dir: '{{ replace "internal" "internal/mocks" 1 .InterfaceDir}}'
template: testify
packages:
  ./internal/domains/product:
  ./internal/repositories:
