// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package product_mock

import (
	"github.com/Touutae-labs/simple-gin/internal/models"
	"github.com/shopspring/decimal"
	mock "github.com/stretchr/testify/mock"
)

// NewMockModule creates a new instance of MockModule. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockModule(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockModule {
	mock := &MockModule{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockModule is an autogenerated mock type for the Module type
type MockModule struct {
	mock.Mock
}

type MockModule_Expecter struct {
	mock *mock.Mock
}

func (_m *MockModule) EXPECT() *MockModule_Expecter {
	return &MockModule_Expecter{mock: &_m.Mock}
}

// ValidateCreate provides a mock function for the type MockModule
func (_mock *MockModule) ValidateCreate(name string, description *string, price decimal.Decimal) *models.Error {
	ret := _mock.Called(name, description, price)

	if len(ret) == 0 {
		panic("no return value specified for ValidateCreate")
	}

	var r0 *models.Error
	if returnFunc, ok := ret.Get(0).(func(string, *string, decimal.Decimal) *models.Error); ok {
		r0 = returnFunc(name, description, price)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Error)
		}
	}
	return r0
}

// MockModule_ValidateCreate_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ValidateCreate'
type MockModule_ValidateCreate_Call struct {
	*mock.Call
}

// ValidateCreate is a helper method to define mock.On call
//   - name string
//   - description *string
//   - price decimal.Decimal
func (_e *MockModule_Expecter) ValidateCreate(name interface{}, description interface{}, price interface{}) *MockModule_ValidateCreate_Call {
	return &MockModule_ValidateCreate_Call{Call: _e.mock.On("ValidateCreate", name, description, price)}
}

func (_c *MockModule_ValidateCreate_Call) Run(run func(name string, description *string, price decimal.Decimal)) *MockModule_ValidateCreate_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 *string
		if args[1] != nil {
			arg1 = args[1].(*string)
		}
		var arg2 decimal.Decimal
		if args[2] != nil {
			arg2 = args[2].(decimal.Decimal)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockModule_ValidateCreate_Call) Return(error *models.Error) *MockModule_ValidateCreate_Call {
	_c.Call.Return(error)
	return _c
}

func (_c *MockModule_ValidateCreate_Call) RunAndReturn(run func(name string, description *string, price decimal.Decimal) *models.Error) *MockModule_ValidateCreate_Call {
	_c.Call.Return(run)
	return _c
}

// ValidateListFilter provides a mock function for the type MockModule
func (_mock *MockModule) ValidateListFilter(f *models.ListFilter) *models.Error {
	ret := _mock.Called(f)

	if len(ret) == 0 {
		panic("no return value specified for ValidateListFilter")
	}

	var r0 *models.Error
	if returnFunc, ok := ret.Get(0).(func(*models.ListFilter) *models.Error); ok {
		r0 = returnFunc(f)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Error)
		}
	}
	return r0
}

// MockModule_ValidateListFilter_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ValidateListFilter'
type MockModule_ValidateListFilter_Call struct {
	*mock.Call
}

// ValidateListFilter is a helper method to define mock.On call
//   - f *models.ListFilter
func (_e *MockModule_Expecter) ValidateListFilter(f interface{}) *MockModule_ValidateListFilter_Call {
	return &MockModule_ValidateListFilter_Call{Call: _e.mock.On("ValidateListFilter", f)}
}

func (_c *MockModule_ValidateListFilter_Call) Run(run func(f *models.ListFilter)) *MockModule_ValidateListFilter_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *models.ListFilter
		if args[0] != nil {
			arg0 = args[0].(*models.ListFilter)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockModule_ValidateListFilter_Call) Return(error *models.Error) *MockModule_ValidateListFilter_Call {
	_c.Call.Return(error)
	return _c
}

func (_c *MockModule_ValidateListFilter_Call) RunAndReturn(run func(f *models.ListFilter) *models.Error) *MockModule_ValidateListFilter_Call {
	_c.Call.Return(run)
	return _c
}

// ValidatePatch provides a mock function for the type MockModule
func (_mock *MockModule) ValidatePatch(name *string, description *string, price *decimal.Decimal) *models.Error {
	ret := _mock.Called(name, description, price)

	if len(ret) == 0 {
		panic("no return value specified for ValidatePatch")
	}

	var r0 *models.Error
	if returnFunc, ok := ret.Get(0).(func(*string, *string, *decimal.Decimal) *models.Error); ok {
		r0 = returnFunc(name, description, price)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Error)
		}
	}
	return r0
}

// MockModule_ValidatePatch_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ValidatePatch'
type MockModule_ValidatePatch_Call struct {
	*mock.Call
}

// ValidatePatch is a helper method to define mock.On call
//   - name *string
//   - description *string
//   - price *decimal.Decimal
func (_e *MockModule_Expecter) ValidatePatch(name interface{}, description interface{}, price interface{}) *MockModule_ValidatePatch_Call {
	return &MockModule_ValidatePatch_Call{Call: _e.mock.On("ValidatePatch", name, description, price)}
}

func (_c *MockModule_ValidatePatch_Call) Run(run func(name *string, description *string, price *decimal.Decimal)) *MockModule_ValidatePatch_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *string
		if args[0] != nil {
			arg0 = args[0].(*string)
		}
		var arg1 *string
		if args[1] != nil {
			arg1 = args[1].(*string)
		}
		var arg2 *decimal.Decimal
		if args[2] != nil {
			arg2 = args[2].(*decimal.Decimal)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockModule_ValidatePatch_Call) Return(error *models.Error) *MockModule_ValidatePatch_Call {
	_c.Call.Return(error)
	return _c
}

func (_c *MockModule_ValidatePatch_Call) RunAndReturn(run func(name *string, description *string, price *decimal.Decimal) *models.Error) *MockModule_ValidatePatch_Call {
	_c.Call.Return(run)
	return _c
}
