// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package product_mock

import (
	"context"

	"github.com/Touutae-labs/simple-gin/internal/models"
	mock "github.com/stretchr/testify/mock"
)

// NewMockRepository creates a new instance of MockRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockRepository {
	mock := &MockRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockRepository is an autogenerated mock type for the Repository type
type MockRepository struct {
	mock.Mock
}

type MockRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockRepository) EXPECT() *MockRepository_Expecter {
	return &MockRepository_Expecter{mock: &_m.Mock}
}

// Create provides a mock function for the type MockRepository
func (_mock *MockRepository) Create(ctx context.Context, in models.CreateInput) (string, error) {
	ret := _mock.Called(ctx, in)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, models.CreateInput) (string, error)); ok {
		return returnFunc(ctx, in)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, models.CreateInput) string); ok {
		r0 = returnFunc(ctx, in)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, models.CreateInput) error); ok {
		r1 = returnFunc(ctx, in)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - in models.CreateInput
func (_e *MockRepository_Expecter) Create(ctx interface{}, in interface{}) *MockRepository_Create_Call {
	return &MockRepository_Create_Call{Call: _e.mock.On("Create", ctx, in)}
}

func (_c *MockRepository_Create_Call) Run(run func(ctx context.Context, in models.CreateInput)) *MockRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 models.CreateInput
		if args[1] != nil {
			arg1 = args[1].(models.CreateInput)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockRepository_Create_Call) Return(s string, err error) *MockRepository_Create_Call {
	_c.Call.Return(s, err)
	return _c
}

func (_c *MockRepository_Create_Call) RunAndReturn(run func(ctx context.Context, in models.CreateInput) (string, error)) *MockRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// GetByID provides a mock function for the type MockRepository
func (_mock *MockRepository) GetByID(ctx context.Context, id string) (*models.Product, error) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetByID")
	}

	var r0 *models.Product
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*models.Product, error)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *models.Product); ok {
		r0 = returnFunc(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Product)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRepository_GetByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByID'
type MockRepository_GetByID_Call struct {
	*mock.Call
}

// GetByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
func (_e *MockRepository_Expecter) GetByID(ctx interface{}, id interface{}) *MockRepository_GetByID_Call {
	return &MockRepository_GetByID_Call{Call: _e.mock.On("GetByID", ctx, id)}
}

func (_c *MockRepository_GetByID_Call) Run(run func(ctx context.Context, id string)) *MockRepository_GetByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockRepository_GetByID_Call) Return(product *models.Product, err error) *MockRepository_GetByID_Call {
	_c.Call.Return(product, err)
	return _c
}

func (_c *MockRepository_GetByID_Call) RunAndReturn(run func(ctx context.Context, id string) (*models.Product, error)) *MockRepository_GetByID_Call {
	_c.Call.Return(run)
	return _c
}

// List provides a mock function for the type MockRepository
func (_mock *MockRepository) List(ctx context.Context, f *models.ListFilter) (*models.ListPage, error) {
	ret := _mock.Called(ctx, f)

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 *models.ListPage
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *models.ListFilter) (*models.ListPage, error)); ok {
		return returnFunc(ctx, f)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *models.ListFilter) *models.ListPage); ok {
		r0 = returnFunc(ctx, f)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.ListPage)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *models.ListFilter) error); ok {
		r1 = returnFunc(ctx, f)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRepository_List_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'List'
type MockRepository_List_Call struct {
	*mock.Call
}

// List is a helper method to define mock.On call
//   - ctx context.Context
//   - f *models.ListFilter
func (_e *MockRepository_Expecter) List(ctx interface{}, f interface{}) *MockRepository_List_Call {
	return &MockRepository_List_Call{Call: _e.mock.On("List", ctx, f)}
}

func (_c *MockRepository_List_Call) Run(run func(ctx context.Context, f *models.ListFilter)) *MockRepository_List_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *models.ListFilter
		if args[1] != nil {
			arg1 = args[1].(*models.ListFilter)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockRepository_List_Call) Return(listPage *models.ListPage, err error) *MockRepository_List_Call {
	_c.Call.Return(listPage, err)
	return _c
}

func (_c *MockRepository_List_Call) RunAndReturn(run func(ctx context.Context, f *models.ListFilter) (*models.ListPage, error)) *MockRepository_List_Call {
	_c.Call.Return(run)
	return _c
}

// Patch provides a mock function for the type MockRepository
func (_mock *MockRepository) Patch(ctx context.Context, id string, in models.PatchInput) (*models.Product, error) {
	ret := _mock.Called(ctx, id, in)

	if len(ret) == 0 {
		panic("no return value specified for Patch")
	}

	var r0 *models.Product
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, models.PatchInput) (*models.Product, error)); ok {
		return returnFunc(ctx, id, in)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, models.PatchInput) *models.Product); ok {
		r0 = returnFunc(ctx, id, in)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Product)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, models.PatchInput) error); ok {
		r1 = returnFunc(ctx, id, in)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRepository_Patch_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Patch'
type MockRepository_Patch_Call struct {
	*mock.Call
}

// Patch is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
//   - in models.PatchInput
func (_e *MockRepository_Expecter) Patch(ctx interface{}, id interface{}, in interface{}) *MockRepository_Patch_Call {
	return &MockRepository_Patch_Call{Call: _e.mock.On("Patch", ctx, id, in)}
}

func (_c *MockRepository_Patch_Call) Run(run func(ctx context.Context, id string, in models.PatchInput)) *MockRepository_Patch_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 models.PatchInput
		if args[2] != nil {
			arg2 = args[2].(models.PatchInput)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockRepository_Patch_Call) Return(product *models.Product, err error) *MockRepository_Patch_Call {
	_c.Call.Return(product, err)
	return _c
}

func (_c *MockRepository_Patch_Call) RunAndReturn(run func(ctx context.Context, id string, in models.PatchInput) (*models.Product, error)) *MockRepository_Patch_Call {
	_c.Call.Return(run)
	return _c
}

// SoftDelete provides a mock function for the type MockRepository
func (_mock *MockRepository) SoftDelete(ctx context.Context, id string) error {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for SoftDelete")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = returnFunc(ctx, id)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockRepository_SoftDelete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SoftDelete'
type MockRepository_SoftDelete_Call struct {
	*mock.Call
}

// SoftDelete is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
func (_e *MockRepository_Expecter) SoftDelete(ctx interface{}, id interface{}) *MockRepository_SoftDelete_Call {
	return &MockRepository_SoftDelete_Call{Call: _e.mock.On("SoftDelete", ctx, id)}
}

func (_c *MockRepository_SoftDelete_Call) Run(run func(ctx context.Context, id string)) *MockRepository_SoftDelete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockRepository_SoftDelete_Call) Return(err error) *MockRepository_SoftDelete_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockRepository_SoftDelete_Call) RunAndReturn(run func(ctx context.Context, id string) error) *MockRepository_SoftDelete_Call {
	_c.Call.Return(run)
	return _c
}
