// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package product_mock

import (
	"context"

	"github.com/Touutae-labs/simple-gin/internal/models"
	mock "github.com/stretchr/testify/mock"
)

// NewMockService creates a new instance of MockService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockService {
	mock := &MockService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockService is an autogenerated mock type for the Service type
type MockService struct {
	mock.Mock
}

type MockService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockService) EXPECT() *MockService_Expecter {
	return &MockService_Expecter{mock: &_m.Mock}
}

// Create provides a mock function for the type MockService
func (_mock *MockService) Create(ctx context.Context, in models.CreateInput) (models.Result, *models.Error) {
	ret := _mock.Called(ctx, in)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 models.Result
	var r1 *models.Error
	if returnFunc, ok := ret.Get(0).(func(context.Context, models.CreateInput) (models.Result, *models.Error)); ok {
		return returnFunc(ctx, in)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, models.CreateInput) models.Result); ok {
		r0 = returnFunc(ctx, in)
	} else {
		r0 = ret.Get(0).(models.Result)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, models.CreateInput) *models.Error); ok {
		r1 = returnFunc(ctx, in)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*models.Error)
		}
	}
	return r0, r1
}

// MockService_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockService_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - in models.CreateInput
func (_e *MockService_Expecter) Create(ctx interface{}, in interface{}) *MockService_Create_Call {
	return &MockService_Create_Call{Call: _e.mock.On("Create", ctx, in)}
}

func (_c *MockService_Create_Call) Run(run func(ctx context.Context, in models.CreateInput)) *MockService_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 models.CreateInput
		if args[1] != nil {
			arg1 = args[1].(models.CreateInput)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockService_Create_Call) Return(result models.Result, error *models.Error) *MockService_Create_Call {
	_c.Call.Return(result, error)
	return _c
}

func (_c *MockService_Create_Call) RunAndReturn(run func(ctx context.Context, in models.CreateInput) (models.Result, *models.Error)) *MockService_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function for the type MockService
func (_mock *MockService) Delete(ctx context.Context, id string) *models.Error {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 *models.Error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *models.Error); ok {
		r0 = returnFunc(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Error)
		}
	}
	return r0
}

// MockService_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type MockService_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
func (_e *MockService_Expecter) Delete(ctx interface{}, id interface{}) *MockService_Delete_Call {
	return &MockService_Delete_Call{Call: _e.mock.On("Delete", ctx, id)}
}

func (_c *MockService_Delete_Call) Run(run func(ctx context.Context, id string)) *MockService_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockService_Delete_Call) Return(error *models.Error) *MockService_Delete_Call {
	_c.Call.Return(error)
	return _c
}

func (_c *MockService_Delete_Call) RunAndReturn(run func(ctx context.Context, id string) *models.Error) *MockService_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// Get provides a mock function for the type MockService
func (_mock *MockService) Get(ctx context.Context, id string) (*models.Product, *models.Error) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 *models.Product
	var r1 *models.Error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*models.Product, *models.Error)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *models.Product); ok {
		r0 = returnFunc(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Product)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) *models.Error); ok {
		r1 = returnFunc(ctx, id)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*models.Error)
		}
	}
	return r0, r1
}

// MockService_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type MockService_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
func (_e *MockService_Expecter) Get(ctx interface{}, id interface{}) *MockService_Get_Call {
	return &MockService_Get_Call{Call: _e.mock.On("Get", ctx, id)}
}

func (_c *MockService_Get_Call) Run(run func(ctx context.Context, id string)) *MockService_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockService_Get_Call) Return(product *models.Product, error *models.Error) *MockService_Get_Call {
	_c.Call.Return(product, error)
	return _c
}

func (_c *MockService_Get_Call) RunAndReturn(run func(ctx context.Context, id string) (*models.Product, *models.Error)) *MockService_Get_Call {
	_c.Call.Return(run)
	return _c
}

// List provides a mock function for the type MockService
func (_mock *MockService) List(ctx context.Context, f *models.ListFilter) (*models.ListPage, *models.Error) {
	ret := _mock.Called(ctx, f)

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 *models.ListPage
	var r1 *models.Error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *models.ListFilter) (*models.ListPage, *models.Error)); ok {
		return returnFunc(ctx, f)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *models.ListFilter) *models.ListPage); ok {
		r0 = returnFunc(ctx, f)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.ListPage)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *models.ListFilter) *models.Error); ok {
		r1 = returnFunc(ctx, f)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*models.Error)
		}
	}
	return r0, r1
}

// MockService_List_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'List'
type MockService_List_Call struct {
	*mock.Call
}

// List is a helper method to define mock.On call
//   - ctx context.Context
//   - f *models.ListFilter
func (_e *MockService_Expecter) List(ctx interface{}, f interface{}) *MockService_List_Call {
	return &MockService_List_Call{Call: _e.mock.On("List", ctx, f)}
}

func (_c *MockService_List_Call) Run(run func(ctx context.Context, f *models.ListFilter)) *MockService_List_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *models.ListFilter
		if args[1] != nil {
			arg1 = args[1].(*models.ListFilter)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockService_List_Call) Return(listPage *models.ListPage, error *models.Error) *MockService_List_Call {
	_c.Call.Return(listPage, error)
	return _c
}

func (_c *MockService_List_Call) RunAndReturn(run func(ctx context.Context, f *models.ListFilter) (*models.ListPage, *models.Error)) *MockService_List_Call {
	_c.Call.Return(run)
	return _c
}

// Patch provides a mock function for the type MockService
func (_mock *MockService) Patch(ctx context.Context, id string, in models.PatchInput) (models.Result, *models.Error) {
	ret := _mock.Called(ctx, id, in)

	if len(ret) == 0 {
		panic("no return value specified for Patch")
	}

	var r0 models.Result
	var r1 *models.Error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, models.PatchInput) (models.Result, *models.Error)); ok {
		return returnFunc(ctx, id, in)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, models.PatchInput) models.Result); ok {
		r0 = returnFunc(ctx, id, in)
	} else {
		r0 = ret.Get(0).(models.Result)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, models.PatchInput) *models.Error); ok {
		r1 = returnFunc(ctx, id, in)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*models.Error)
		}
	}
	return r0, r1
}

// MockService_Patch_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Patch'
type MockService_Patch_Call struct {
	*mock.Call
}

// Patch is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
//   - in models.PatchInput
func (_e *MockService_Expecter) Patch(ctx interface{}, id interface{}, in interface{}) *MockService_Patch_Call {
	return &MockService_Patch_Call{Call: _e.mock.On("Patch", ctx, id, in)}
}

func (_c *MockService_Patch_Call) Run(run func(ctx context.Context, id string, in models.PatchInput)) *MockService_Patch_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 models.PatchInput
		if args[2] != nil {
			arg2 = args[2].(models.PatchInput)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockService_Patch_Call) Return(result models.Result, error *models.Error) *MockService_Patch_Call {
	_c.Call.Return(result, error)
	return _c
}

func (_c *MockService_Patch_Call) RunAndReturn(run func(ctx context.Context, id string, in models.PatchInput) (models.Result, *models.Error)) *MockService_Patch_Call {
	_c.Call.Return(run)
	return _c
}
