// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package di

import (
	"github.com/Touutae-labs/simple-gin/internal/configurations"
	"github.com/Touutae-labs/simple-gin/internal/controllers"
	"github.com/Touutae-labs/simple-gin/internal/domains/product"
	"github.com/Touutae-labs/simple-gin/internal/server"
	"github.com/google/wire"
)

// Injectors from wire.go:

func Initialize(cfg configurations.Config, title server.ServerTitle, version server.ServerVersion) (*Application, func(), error) {
	serverConfig := cfg.Server
	serverServerConfig := server.BuildServerConfig(serverConfig, title, version)
	healthController := controllers.NewHealthController()
	module := product.New()
	databaseConfig := cfg.Database
	db, cleanup, err := provideDB(databaseConfig)
	if err != nil {
		return nil, nil, err
	}
	repository := provideProductRepository(db)
	service := product.NewService(module, repository)
	productController := controllers.NewProductController(service)
	controllersControllers := controllers.NewControllers(healthController, productController)
	serverServer := provideServer(serverServerConfig, controllersControllers)
	application := &Application{
		Server: serverServer,
		DB:     db,
	}
	return application, func() {
		cleanup()
	}, nil
}

// wire.go:

var serverSet = wire.NewSet(wire.FieldsOf(new(configurations.Config), "Server"), server.BuildServerConfig, provideServer)

var controllersSet = wire.NewSet(controllers.NewHealthController, controllers.NewProductController, controllers.NewControllers)

var productSet = wire.NewSet(product.New, product.NewService)

var repositorySet = wire.NewSet(
	provideProductRepository,
)

var dbSet = wire.NewSet(wire.FieldsOf(new(configurations.Config), "Database"), provideDB)
